language: cpp

install:
  - |
    mkdir deps_build && \
    cd deps_build && \
    cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../third_party/XRT/src && \
    make -j4 DESTDIR=$PWD install

script: mkdir build && cd build