include ../../rules/xocc.mk
include ../../rules/vadd.mk

USER_XOCC_COMPILE_OPT = --user_ip_repo_paths $(USER_IP_REPO)

USER_XOCC_LINK_OPT = --user_ip_repo_paths $(USER_IP_REPO)

all: vadd_kernel_hw_all.xclbin