if(DEFINED ENV{CI})
    if($ENV{CI} STREQUAL "YES")
        message("CI environment variable is set to YES. Treat as running in CI environment. Build for coverage.")
        set(CMAKE_CXX_FLAGS "-g -O0 -Wall -fprofile-arcs -ftest-coverage")
    elseif($ENV{CI} STREQUAL "NO")
        message("CI environment variable is set to NO. Treat as running in local environment. Build for release.")
    else()
        message("CI environment variable is set to unknown value. Treat as running in local environment. Build for release.")
    endif()
else()
    message("CI environment variable is not found. Treat as running in local environment. Build for release.")
endif()